### ISSUE TITLE
feature-search

### ISSUE THREAD

**Issue by gusmiller** [gusmiller/Travel_Researcher#6]
Build the search.HTML, connected to the home screen.

- User will be able to enter the flight parameters. 
- Application will connect to the flight Aviation Stack API and retrieve data in Json format.
- Json file is parsed and information extracted
- Parsed information is displayed on a table element.
- User will be able to select flight that suits better. Selecting button is added dynamically via JQuery.
- When user selects the flight information is saved on the local storage.
- Popup form will display selected flight and user will be prompted for hotels.

**Comment by gusmiller** [comment]
Let me know if you help implementing either the html or the JS

**Comment by gusmiller** [comment]
The popup-up and button functionality is implemented as follow:

For the popup:
- add html code from the tabletest.html (line 11 to 62) and place it into your search.html after your <body> tag. This is your popup. At time I created this form we were using the Aviation API so I am not sure you have changed or added fields. Review the popup form.
- change the <input> tags on the popup form to match your data

Javascript code

- From the hovertable.js copy code from lines 74 to 81 and place it in your init() section
- copy function revealButton() lines 37-66
- copy function removeButton() lines 26-35
- copy function selectRow() lines 6- 24
- and finally copy line 4 and put it at the top of your JS.
- you need to pull changes from developing first

Special case for Jacob 
 you will have to change the <input> tags to match your data, as well the id names for each section. In the code from line 17-22 you change accordingly

**Comment by SonjaGorin** [comment]
We've decided to switch to Tequila API because Aviation Stack was not giving us the results we needed.

**Comment by SonjaGorin** [comment]
The search page is working as expected:
- User chooses Departure and Destination city from provided menu options;
- User chooses the Departure date from the provided calendar;
- When the user clicks on the Search button the table of 10 flights shows up;
- The table has information about the flight: 
          - Departure time
          - Arrival time
          - Flight duration
          - Flight number
          - Flight price
- User can click on a Save flight button if they like the information. 
- The Save button saves all the information about the flight to the local storage.

**Comment by gusmiller** [comment]
Sonja; please enter the comments we discussed on last meeting

**Comment by SonjaGorin** [comment]
I opened issues for everything we talked about yesterday.

**Comment by SonjaGorin** [comment]
I also added the header to my search html page.

**Comment by gusmiller** [comment]
I can see that Sonja has complete styling the core-search engine! 
Well done!

![Search Core Engine](https://github.com/gusmiller/Travel_Researcher/assets/10382486/bc7d2ec7-95a1-4ecb-8023-ec91aede4b68)

**Comment by SonjaGorin** [comment]
Thank you. I still want to add more styling.

**Comment by SonjaGorin** [comment]
Done
