### ISSUE TITLE
Bug: aviationstack not returning future flights

### ISSUE THREAD

**Issue by gusmiller** [gusmiller/Travel_Researcher#8]
Aviation Stack API not returning future flights.
- search for another API

**Comment by gusmiller** [comment]
If the API is not returning future flight then it has to be changed. Find another API

**Comment by SonjaGorin** [comment]
The API from Aviation Stack was returning only current day and past flights. That's why we decided to switch to Tequila API. Tequila API returns future flights so we were able to get the results we were looking for.
